[package]
name = "game_model"
version = "0.4.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", branch = "feature/829/sprite-render-pass" }
derive-new = "0.5"
heck = "0.3"
itertools = "~0.7.8"
log = "0.4"
object_model = { path = "../object_model" }
strum = "0.10"
strum_macros = "0.10"

[dev-dependencies]
tempfile = "3.0"
