[package]
name = "game_model"
version = "0.5.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
derive-new = "0.5"
derive_builder = "0.6"
map_model = { path = "../map_model" }
object_model = { path = "../object_model" }
strum = "0.10"
strum_macros = "0.10"

[dev-dependencies]
tempfile = "3.0"
