[package]
name = "game_model"
version = "0.11.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["vulkan"] }
asset_model = { path = "../asset_model" }
character_prefab = { path = "../character_prefab" }
derive-new = "0.5.6"
energy_prefab = { path = "../energy_prefab" }
map_model = { path = "../map_model" }
object_type = { path = "../object_type" }

[features]
nightly = ["amethyst/nightly"]
