[package]
name = "game_model"
version = "0.4.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
derive_more = "0.11"
itertools = "~0.7.8"
log = "0.4"
object_model = { path = "../object_model" }

[dev-dependencies]
tempfile = "3.0"
