[package]
name = "game_model"
version = "0.9.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
asset_model = { path = "../asset_model" }
character_loading = { path = "../character_loading" }
derive-new = "0.5.6"
map_model = { path = "../map_model" }
object_model = { path = "../object_model" }

[build-dependencies]
rustc_version = "0.2.3"
