[package]
name = "map_play"
version = "0.5.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", branch = "bugfix/929/fix-sprite-position" }
map_model = { path = "../map_model" }
derive-new = "0.5"
typename = "0.1"
typename_derive = "0.1"

[dev-dependencies]
amethyst_test_support = { path = "../amethyst_test_support" }

[features]
nightly = ["amethyst/nightly", "amethyst_test_support/nightly"]
