[package]
name = "map_play"
version = "0.8.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
map_model = { path = "../map_model" }
derive-new = "0.5.6"
typename = "0.1.0"
typename_derive = "0.1.1"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }

[features]
nightly = ["amethyst/nightly", "amethyst_test/nightly"]

[build-dependencies]
rustc_version = "0.2.3"

