[package]
name = "session_server"
version = "0.18.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "maintenance/correct-amethyst-test-features", default-features = false, features = ["network"] }
frame_rate = { path = "../../crate/frame_rate" }
network_join_play = { path = "../../crate/network_join_play" }
serde_yaml = "0.8.11"
structopt = "0.3.9"
structopt-derive = "0.4.2"
