[package]
name = "map_selection"
version = "0.9.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application_event = { path = "../application_event" }
application_state = { path = "../application_state" }
asset_model = { path = "../asset_model" }
derivative = "1.0.2"
derive-new = "0.5.6"
game_model = { path = "../game_model" }
log = "0.4.6"
map_selection_model = { path = "../map_selection_model" }
state_registry = { path = "../state_registry" }
typename = "0.1.0"
typename_derive = "0.1.1"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
asset_loading = { path = "../asset_loading" }
assets_test = { path = "../assets_test" }
loading = { path = "../loading" }
map_loading = { path = "../map_loading" }
sequence_loading = { path = "../sequence_loading" }

[features]
nightly = ["amethyst/nightly"]
