[package]
name = "map_selection"
version = "0.6.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application_event = { path = "../application_event" }
application_state = { path = "../application_state" }
derivative = "1.0"
derive-new = "0.5"
game_model = { path = "../game_model" }
log = "0.4"
map_selection_model = { path = "../map_selection_model" }
typename = "0.1"
typename_derive = "0.1"

[dev-dependencies]
amethyst_test_support = { path = "../amethyst_test_support" }
asset_loading = { path = "../asset_loading" }
assets_test = { path = "../assets_test" }
loading = { path = "../loading" }
map_loading = { path = "../map_loading" }

[features]
nightly = ["amethyst/nightly", "amethyst_test_support/nightly"]
