[package]
name = "map_selection"
version = "0.5.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", branch = "feature/829/sprite-render-pass" }
derivative = "1.0"
derive-new = "0.5"
game_model = { path = "../game_model" }
log = "0.4"
map_model = { path = "../map_model" }
typename = "0.1"
typename_derive = "0.1"

[dev-dependencies]
amethyst_test_support = { path = "../amethyst_test_support" }

[features]
nightly = ["amethyst/nightly", "amethyst_test_support/nightly"]
