[package]
name = "character_selection_stdio"
version = "0.7.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application_event = { path = "../application_event" }
character_selection_model = { path = "../character_selection_model" }
derive-new = "0.5"
game_input = { path = "../game_input" }
game_model = { path = "../game_model" }
stdio_spi = { path = "../stdio_spi" }
structopt = "0.2"
structopt-derive = "0.2"
typename = "0.1"
typename_derive = "0.1"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
application_test_support = { path = "../application_test_support" }
assets_test = { path = "../assets_test" }
