[package]
name = "character_selection_stdio"
version = "0.12.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["vulkan"] }
application_event = { path = "../application_event" }
asset_model = { path = "../asset_model" }
character_selection_model = { path = "../character_selection_model" }
derive-new = "0.5.6"
game_input_model = { path = "../game_input_model" }
game_model = { path = "../game_model" }
stdio_spi = { path = "../stdio_spi" }
structopt = "0.2.18"
structopt-derive = "0.2.18"
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["test-support", "vulkan"] }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
application_test_support = { path = "../application_test_support" }
assets_test = { path = "../assets_test" }

[features]
nightly = ["amethyst/nightly"]
