[package]
name = "object_type"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
strum = "0.15.0"
strum_macros = "0.15.0"

[features]
default = []
test-support = []
