[package]
name = "map_selection_model"
version = "0.8.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst_utils = { git = "https://github.com/amethyst/amethyst.git" }
game_model = { path = "../game_model" }
map_model = { path = "../map_model" }

[build-dependencies]
rustc_version = "0.2.3"

