[package]
name = "map_selection_model"
version = "0.6.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst_utils = { git = "https://github.com/amethyst/amethyst.git" }
game_model = { path = "../game_model" }
map_model = { path = "../map_model" }
