[package]
name = "map_selection_model"
version = "0.9.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
asset_model = { path = "../asset_model" }
map_model = { path = "../map_model" }

[features]
nightly = ["amethyst/nightly"]
