[package]
name = "state_play"
version = "0.15.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
asset_model = { path = "../asset_model" }
background_play = { path = "../background_play" }
derivative = "1.0.3"
derive-new = "0.5.8"
kinematic_model = { path = "../kinematic_model" }
log = "0.4.8"
state_registry = { path = "../state_registry" }
tracker = { path = "../tracker" }
typename = "0.1.1"
typename_derive = "0.1.3"

[features]
nightly = ["amethyst/nightly"]
