[package]
name = "game_mode_selection_stdio"
version = "0.9.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application_event = { path = "../application_event" }
application_menu = { path = "../application_menu" }
game_mode_selection_model = { path = "../game_mode_selection_model" }
derive-new = "0.5.6"
stdio_spi = { path = "../stdio_spi" }
structopt = "0.2.14"
structopt-derive = "0.2.14"
typename = "0.1.0"
typename_derive = "0.1.1"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
assets_test = { path = "../assets_test" }

[build-dependencies]
rustc_version = "0.2.3"

