[package]
name = "sprite_model"
version = "0.6.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
derive-new = "0.5"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
toml = "0.4"
