[package]
name = "sprite_model"
version = "0.9.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
derive-new = "0.5.6"
sequence_model_spi = { path = "../sequence_model_spi" }
serde = "1.0.87"
specs-derive = "0.4.0"

[dev-dependencies]
toml = "0.4.10"

[features]
nightly = ["amethyst/nightly"]
