[package]
name = "logic_clock_derive"
version = "0.11.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.30"
proc_macro_roids = "0.2.1"
quote = "0.6.12"
syn = { version = "0.15.34", features = ["extra-traits", "visit"] }
