.install_dependencies_template: &install_dependencies
  stage: test
  before_script:
    - apt-get update -qq && apt-get install -y -qq libcurl4-openssl-dev libelf-dev libdw-dev cmake gcc binutils-dev
    - cargo install cargo-make

stable:build:
  # https://hub.docker.com/r/library/rust/tags/
  # https://github.com/rust-lang-nursery/docker-rust
  image: "rust:latest"
  <<: *install_dependencies
  script:
    - cargo make workspace-ci-flow

nightly:build:
  # https://hub.docker.com/r/rustlang/rust/tags/
  image: "rustlang/rust:nightly"
  variables:
    CARGO_MAKE_RUN_CODECOV: 'true'
  <<: *install_dependencies
  script:
    - cargo make workspace-ci-flow
  after_script:
    - cargo make --no-workspace workspace-coverage
