.install_dependencies_template: &install_dependencies
  stage: test
  before_script:
    - apt-get update -qq && apt-get install -y -qq libcurl4-openssl-dev libelf-dev libdw-dev cmake gcc binutils-dev zlib1g-dev libiberty-dev
    - cargo install cargo-make

.cache_artifacts_template: &cache_artifacts
  cache:
    paths:
      - target/
      - cargo/

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

stable:build:
  # https://hub.docker.com/r/library/rust/tags/
  # https://github.com/rust-lang-nursery/docker-rust
  image: "rust:latest"
  variables:
    CARGO_MAKE_SKIP_CODECOV: 'true'
  <<: *install_dependencies
  <<: *cache_artifacts
  script:
    - cargo make workspace-ci-flow

nightly:build:
  # https://hub.docker.com/r/rustlang/rust/tags/
  image: "rustlang/rust:nightly"
  variables:
    CARGO_MAKE_RUN_CODECOV: 'true'
  <<: *install_dependencies
  <<: *cache_artifacts
  script:
    - cargo make workspace-ci-flow
  after_script:
    - cargo make --no-workspace workspace-coverage
