# === Templates === #
# These are commonized definitions used across the stage definitions.
# Scroll down to the `CI Stages` section for the stage definitions.

# Artifacts transferred between different stages of jobs
.artifacts_build: &artifacts_build
  artifacts:
    # Send all files in target
    paths:
      - target/
    expire_in: 3 days

.cache_build: &cache_build
  cache:
    # We don't cache target/ as well because old binaries interfere with coverage
    paths:
      # Build dependencies (dependent crates)
      - cargo/ 

.cache_test: &cache_test
  cache:
    # We don't cache target/ as well because old binaries interfere with coverage
    paths:
      - kcov-$KCOV_VERSION

# https://hub.docker.com/r/rustlang/rust/tags/
.rust_image_nightly: &rust_image_nightly "rustlang/rust:nightly"

# https://hub.docker.com/r/library/rust/tags/
# https://github.com/rust-lang-nursery/docker-rust
.rust_image_stable: &rust_image_stable "rust:latest"

.install_dependencies_build: &install_dependencies_build
  before_script:
    - cargo --version -v
    - rustc --version -v
    - apt-get update -qq
    - |
      pkgs=(
        # amethyst
        libasound2-dev

        # enigo
        libxtst-dev
      )
      apt-get install -y -qq "${pkgs[@]}"

    # Automated crate security audit
    - cargo --list | grep -F audit || cargo install cargo-audit

.install_dependencies_test: &install_dependencies_test
  before_script:
    - apt-get update -qq
    - |
      pkgs=(
        # kcov
        libcurl4-openssl-dev
        libelf-dev
        libdw-dev
        cmake
        gcc
        binutils-dev
        zlib1g-dev
        libiberty-dev
        zip

        # xvfb
        xvfb
        libgl1-mesa-dev
        libgl1-mesa-glx
        mesa-utils
      )
      apt-get install -y -qq "${pkgs[@]}"
    - cargo install cargo-make --force

.job_nightly: &job_nightly
  image: *rust_image_nightly
  variables:
    CARGO_MAKE_RUN_CODECOV: 'true'
    KCOV_VERSION: 34

.job_stable: &job_stable
  image: *rust_image_stable
  variables:
    CARGO_MAKE_SKIP_CODECOV: 'true'

.xvfb_start: &xvfb_start |
  # Start XVFB
  export DISPLAY=:99.0
  /sbin/start-stop-daemon --start \
                          --quiet \
                          --pidfile /tmp/custom_xvfb_99.pid \
                          --make-pidfile \
                          --background \
                          --exec /usr/bin/Xvfb \
                          -- \
                          :99 \
                          -screen 0 1280x1024x24+32 \
                          -pixdepths 3 27 32 \
                          -ac \
                          +extension GLX \
                          +render \
                          -noreset

.stage_build: &stage_build
  stage: build
  <<: *install_dependencies_build
  <<: *artifacts_build
  <<: *cache_build
  script:
    - cargo audit
    - cargo test --all --no-run

.stage_test: &stage_test
  stage: test
  <<: *install_dependencies_test
  <<: *cache_test
  script:
    - *xvfb_start
    - cargo test --all

# === CI Stages === #

stages:
  - build
  - test

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

nightly:build:
  <<: *stage_build
  <<: *job_nightly

nightly:test:
  <<: *stage_test
  <<: *job_nightly
  dependencies:
    - nightly:build
  after_script:
    - *xvfb_start
    # On gitlab-ci we cannot use sudo to install kcov, which ships with the default Makefile from
    # cargo-make.
    #
    # We have tried overriding the kcov install_script in [tasks.coverage-kcov] in Makefile.toml,
    # but for some reason cargo-make does not use the override. cargo-make does have tests proving
    # that it does use overrides; maybe it's to do with workspace crates.
    #
    # Anyway, we install it ourselves here.
    - |
      # install kcov
      command -v kcov >/dev/null 2>&1 || {
        if [ "$(grep -Ei 'debian|buntu|mint' /etc/*release)" ]; then
          wget https://github.com/SimonKagstrom/kcov/archive/v$KCOV_VERSION.zip
          unzip -uo v$KCOV_VERSION.zip
          cd kcov-$KCOV_VERSION

          build_dir='./build'

          # Uncomment the next line if kcov is not building correctly
          # rm -rf "${build_dir}"

          if ! test -d "${build_dir}"; then mkdir "${build_dir}" ; fi
          cd "${build_dir}"
          cmake ..
          make
          make install
          cd ../..
          # Don't delete previously downloaded files
          # rm -rf kcov-$KCOV_VERSION
        fi
      }
    - cargo make --no-workspace workspace-coverage
    - grep -F merged_files ./target/coverage/index.json | grep -o '"covered":"[0-9]\+\.[0-9]\+"'
  coverage: '/"covered":"\d+\.\d+"/'

stable:build:
  <<: *stage_build
  <<: *job_stable

stable:test:
  <<: *stage_test
  <<: *job_stable
  dependencies:
    - stable:build
