.install_dependencies_template: &install_dependencies
  stage: test
  before_script:
    - cargo install cargo-make

stable:build:
  # https://hub.docker.com/r/library/rust/tags/
  # https://github.com/rust-lang-nursery/docker-rust
  image: "rust:latest"
  <<: *install_dependencies
  script:
    - cargo make workspace-ci-flow

nightly:build:
  # https://hub.docker.com/r/rustlang/rust/tags/
  image: "rustlang/rust:nightly"
  variables:
    CARGO_MAKE_RUN_CODECOV: 'true'
  <<: *install_dependencies
  script:
    - cargo make workspace-ci-flow
    - cargo make --no-workspace workspace-coverage