# === Templates === #
# These are commonized definitions used across the stage definitions.
# Scroll down to the `CI Stages` section for the stage definitions.

.command_build: &command_build cargo test --all --no-run --features ci
.command_test: &command_test cargo test --all --features ci

.install_dependencies_compile_linux: &install_dependencies_compile_linux |
  sudo apt update -qq
  pkgs=(
    # amethyst
    libasound2-dev

    # enigo
    libxtst-dev
  )
  sudo apt install -y -qq "${pkgs[@]}"

.print_tool_versions_linux: &print_tool_versions_linux |
  # Print tool versions
  printf "Shell:\n"
  $0 --version
  printf "\n"

  printf "Cargo:\n"
  cargo --version -v
  printf "\n"

  printf "Rustc:\n"
  rustc --version -v
  printf "\n"

# === CI Stages === #

# Unfortunately we are not able to split `build` and `test` phases -- when we do, the `test` Gitlab
# CI runner is slightly different to the `build` runner, so the artifacts compiled in the `build`
# phase aren't used, and Rust attempts to recompile them in the test phase.
stages:
  - build_and_test

variables:
  # If we do not override `CARGO_HOME`, we must ensure that ALL projects that use the Gitlab runners
  # do not request different versions of tooling, otherwise we run into concurrency issues.
  # Also, we are not able to set it at the this level since we have a Windows runner which does not
  # use the `$VAR` syntax, but `%VAR%`.
  #
  # Furthermore, there is an open bug in Gitlab that Windows is unable to use CI environment
  # variables in .gitlab-ci.yml:
  #
  # See <https://gitlab.com/gitlab-org/gitlab-ce/issues/43337>
  # ---
  # CARGO_HOME: $CI_PROJECT_DIR/cargo
  RUST_BACKTRACE: 1

nightly:conformance:
  stage: build_and_test # piggy backing so that it runs in parallel
  tags:
    - kcov
    - linux
    - rust
    - nightly
  variables:
    RUSTUP_TOOLCHAIN: nightly-x86_64-unknown-linux-gnu
    # Uncomment the next line if clippy is not compatible with the latest nightly.
    # CLIPPY_ENABLED: 'false'
  before_script:
    - *print_tool_versions_linux
    - *install_dependencies_compile_linux
    - build/install_cargo_make.sh

    # For the `cargo --list` commands, we need to pipe stderr to /dev/null because of these issues:
    #
    # * https://github.com/sfackler/cargo-tree/issues/25
    # * https://github.com/rust-lang/rust/issues/46016
    # Automated crate security audit
    - |
      # Install cargo-audit
      existing_crates="$(cargo --list 2>&1)"
      if ! echo "${existing_crates}" | grep -q '\baudit\b' ; then
        cargo install cargo-audit
      fi

    # Automated license checks
    - |
      # Install cargo-license
      existing_crates="$(cargo --list 2>&1)"
      if ! echo "${existing_crates}" | grep -q '\blicense\b'; then
        cargo install cargo-license
      fi

    # Nightly - Rustfmt and Clippy
    - |
      # Install rustfmt and clippy

      # Needed for gitlab-ci
      test -z "${USER}" && export USER=build
      build/install_rustfmt.sh
      build/install_clippy.sh
  script:
    # Code quality, security vulnerability checks, license compatibility
    - cargo make --no-workspace conformance

linux:stable:
  stage: build_and_test
  tags:
    - kcov
    - linux
    - rust
    - stable
    - xvfb
  variables:
    CARGO_MAKE_RUN_CODECOV: 'true'
    RUSTUP_TOOLCHAIN: stable-x86_64-unknown-linux-gnu
  before_script:
    - *print_tool_versions_linux
    - *install_dependencies_compile_linux
    - build/install_cargo_make.sh
  script:
    - *command_build
    - source xvfb_start
    - *command_test
  after_script:
    - cargo make --no-workspace workspace-coverage
    - source xvfb_stop
    - grep -F merged_files ./target/coverage/index.json | grep -o '"covered":"[0-9]\+\.[0-9]\+"'
  coverage: '/"covered":"\d+\.\d+"/'

windows:stable:
  stage: build_and_test
  tags:
    - windows
    - rust
    - stable
  variables:
    RUSTUP_TOOLCHAIN: stable-x86_64-pc-windows-msvc
  before_script:
    - cargo --version -v
    - rustc --version -v
  script:
    - *command_build
    - *command_test
