[workspace]
members = ["app/*", "crate/*"]

[profile.release]
# Slower compilation, but better performance of final executable.
# <https://blog.rust-lang.org/2018/02/15/Rust-1.24.html#incremental-compilation>
codegen-units = 1

[patch.crates-io]
derive_deref = { git = "https://github.com/azriel91/derive_deref.git", branch = "feature/allow-phantom-data-second-field" }
rodio = { git = "https://github.com/azriel91/rodio.git", branch = "use-nalgebra-for-spatial-source" }
