[workspace]
members = ["app/*", "crate/*"]

[profile.release]
# Slower compilation, but better performance of final executable.
# <https://blog.rust-lang.org/2018/02/15/Rust-1.24.html#incremental-compilation>
codegen-units = 1

[patch.crates-io]
derivative = { git = "https://github.com/azriel91/rust-derivative.git", branch = "maintenance/25/bump-syn-and-quote" }
toml = { git = "https://github.com/azriel91/toml-rs.git", branch = "feature/225/externally-tagged-enums" }
