[workspace]
members = ["app/*", "crate/*"]

[profile.release]
# Slower compilation, but better performance of final executable.
# <https://blog.rust-lang.org/2018/02/15/Rust-1.24.html#incremental-compilation>
codegen-units = 1

[patch.crates-io]
andrew = { git = "https://github.com/azriel91/andrew.git", branch = "maintenance/update-dependencies" }
derive_deref = { git = "https://github.com/azriel91/derive_deref.git", branch = "maintenance/update-syn-quote-proc-macro2" }
derive_builder = { git = "https://github.com/colin-kiegel/rust-derive-builder.git" }
derive_more = { git = "https://github.com/JelteF/derive_more.git" }
