# We skip binaries because cargo-make 0.9 runs all binaries under `target/debug/deps`, which include
# both tests and the application. In the case of an interactive application, it just waits for input
# and hangs indefinitely.
#
# This does mean we lose coverage information on binaries, so we should aim to keep them small and
# put most of the logic in library crates.
#
# See https://github.com/sagiegurari/cargo-make/issues/44#issuecomment-353904958
[tasks.workspace-members-coverage.env]
"CARGO_MAKE_MEMBER_TASK" = "coverage"
"CARGO_MAKE_WORKSPACE_SKIP_MEMBERS" = "app/free_will"
