[package]
name = "input_reaction_play"
version = "0.16.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
approx = "0.3.2"
charge_model = { path = "../charge_model" }
derivative = "1.0.3"
derive-new = "0.5.8"
game_input = { path = "../game_input" }
game_input_model = { path = "../game_input_model" }
input_reaction_model = { path = "../input_reaction_model" }
named_type = "0.2.1"
named_type_derive = "0.2.1"
sequence_model = { path = "../sequence_model" }
