[package]
name = "map_model"
version = "0.6.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
derive-new = "0.5"
serde = "1.0"
serde_derive = "1.0"
sprite_loading = { path = "../sprite_loading" }
sprite_model = { path = "../sprite_model" }

[dev-dependencies]
pretty_assertions = "0.5"
toml = "0.4"
