[package]
name = "game_input"
version = "0.9.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
derivative = "1.0.2"
derive-new = "0.5.6"
game_input_model = { path = "../game_input_model" }
log = "0.4.6"
serde = "1.0.85"
strum = "0.13.0"
strum_macros = "0.13.0"
typename = "0.1.0"
typename_derive = "0.1.1"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }

[features]
nightly = ["amethyst/nightly"]
