[package]
name = "game_input"
version = "0.5.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
derivative = "1.0"
derive-new = "0.5"
serde = "1.0"
serde_derive = "1.0"
strum = "0.10"
strum_macros = "0.10"
typename = "0.1"
typename_derive = "0.1"

[dev-dependencies]
application = { path = "../application" }
amethyst_test_support = { path = "../amethyst_test_support" }
hamcrest = "*"
winit = "0.17"
