[package]
name = "game_input"
version = "0.8.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
derivative = "1.0"
derive-new = "0.5"
serde = "1.0"
strum = "0.11"
strum_macros = "0.11"
typename = "0.1"
typename_derive = "0.1"

[dev-dependencies]
application = { path = "../application" }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
hamcrest = "*"
winit = "0.18"
