[package]
name = "object_play"
version = "0.9.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
character_model = { path = "../character_model" }
derive-new = "0.5.6"
game_input = { path = "../game_input" }
object_model = { path = "../object_model" }

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
pretty_assertions = "0.5.1"

[build-dependencies]
rustc_version = "0.2.3"

