[package]
name = "object_play"
version = "0.12.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["vulkan"] }
derivative = "1.0.2"
derive-new = "0.5.6"
kinematic_model = { path = "../kinematic_model" }
map_model = { path = "../map_model" }
map_selection_model = { path = "../map_selection_model" }
object_model = { path = "../object_model" }
shred = "0.7.0"
shred-derive = "0.5.1"
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["test-support", "vulkan"] }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
application_test_support = { path = "../application_test_support" }
pretty_assertions = "0.6.1"

[features]
nightly = ["amethyst/nightly"]
