[package]
name = "object_play"
version = "0.7.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
derive-new = "0.5"
game_input = { path = "../game_input" }
object_model = { path = "../object_model" }
tracker = { path = "../tracker" }
typename = "0.1"
typename_derive = "0.1"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
pretty_assertions = "0.5"
