[package]
name = "object_play"
version = "0.4.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
game_input = { path = "../game_input" }
object_model = { path = "../object_model" }

[dev-dependencies]
pretty_assertions = "0.5"
