[package]
name = "object_play"
version = "0.4.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", branch = "feature/829/sprite-render-pass" }
object_model = { path = "../object_model" }
