[package]
name = "stdio_spi"
version = "0.11.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["vulkan"] }
application_event = { path = "../application_event" }
clap = "2.33.0"
derive-new = "0.5.6"
err-derive = "0.1.5"
log = "0.4.6"
structopt = "0.2.17"
typename = "0.1.1"
typename_derive = "0.1.3"

[features]
nightly = ["amethyst/nightly"]
