[package]
name = "stdio_spi"
version = "0.6.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application_event = { path = "../application_event" }
clap = "2.32"
derive-error-chain = "0.11"
derive-new = "0.5"
error-chain = "0.11"
log = "0.4"
structopt = "0.2"
typename = "0.1"
typename_derive = "0.1"
