[package]
name = "application_event"
version = "0.8.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
character_selection_model = { path = "../character_selection_model" }
derive_more = "0.13.0"
derivative = "1.0.2"
game_mode_selection_model = { path = "../game_mode_selection_model" }
game_play_model = { path = "../game_play_model" }
map_selection_model = { path = "../map_selection_model" }
strum = "0.13.0"
strum_macros = "0.13.0"

[build-dependencies]
rustc_version = "0.2.3"

