[package]
name = "application_event"
version = "0.6.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
character_selection_model = { path = "../character_selection_model" }
derive_more = "0.12.0"
derivative = "1.0"
game_mode_selection_model = { path = "../game_mode_selection_model" }
map_selection_model = { path = "../map_selection_model" }
strum = "0.11"
strum_macros = "0.11"
