[package]
name = "game_mode_selection_ui"
version = "0.7.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application_menu = { path = "../application_menu" }
application_ui = { path = "../application_ui" }
derivative = "1.0"
derive-new = "0.5"
game_mode_selection_model = { path = "../game_mode_selection_model" }
heck = "0.3"
log = "0.4"
strum = "0.11"
typename = "0.1"
typename_derive = "0.1"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }

[features]
nightly = ["amethyst/nightly"]
