[package]
name = "game_mode_selection_ui"
version = "0.9.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application_menu = { path = "../application_menu" }
application_ui = { path = "../application_ui" }
derivative = "1.0.2"
derive-new = "0.5.6"
game_mode_selection_model = { path = "../game_mode_selection_model" }
heck = "0.3.1"
log = "0.4.6"
strum = "0.13.0"
typename = "0.1.0"
typename_derive = "0.1.1"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }

[features]
nightly = ["amethyst/nightly"]
