[package]
name = "game_play_hud"
version = "0.10.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
derive-new = "0.5.6"
specs-derive = "0.4.0"
