[package]
name = "game_play_hud"
version = "0.10.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
asset_gfx_gen = { path = "../asset_gfx_gen" }
derive-new = "0.5.6"
object_model = { path = "../object_model" }
specs-derive = "0.4.0"
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
application_test_support = { path = "../application_test_support" }

[features]
nightly = ["amethyst/nightly"]
