[package]
name = "collision_model"
version = "0.6.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
derive-new = "0.5"
serde = "1.0"
serde_derive = "1.0"
shape_model = { path = "../shape_model" }
