[package]
name = "collision_model"
version = "0.8.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
animation_support = { path = "../animation_support" }
derivative = "1.0.2"
derive-new = "0.5.6"
minterpolate = { version = "0.4.0", features = ["serde"] }
serde = "1.0.85"
shape_model = { path = "../shape_model" }

[dev-dependencies]
pretty_assertions = "0.5.1"
toml = "0.4.10"
