[package]
name = "collision_model"
version = "0.10.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
derivative = "1.0.2"
derive-new = "0.5.6"
derive_deref = "1.0.2"
derive_more = "0.14.0"
logic_clock = { path = "../logic_clock" }
minterpolate = { version = "0.4.0", features = ["serde"] }
numeric_newtype_derive = { path = "../numeric_newtype_derive" }
sequence_model_spi = { path = "../sequence_model_spi" }
serde = "1.0.89"
shape_model = { path = "../shape_model" }
specs-derive = "0.4.0"

[dev-dependencies]
pretty_assertions = "0.6.1"
toml = "0.5.0"

[features]
nightly = ["amethyst/nightly"]
