[package]
name = "collision_model"
version = "0.6.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
animation_support = { path = "../animation_support" }
derivative = "1.0"
derive-new = "0.5"
derive_more = "0.13"
minterpolate = { version = "0.3", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
shape_model = { path = "../shape_model" }

[dev-dependencies]
pretty_assertions = "0.5"
toml = "0.4"
