[package]
name = "character_selection_ui_play"
version = "0.16.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
derivative = "1.0.3"
derive-new = "0.5.8"
character_selection_model = { path = "../character_selection_model" }
character_selection_ui_model = { path = "../character_selection_ui_model" }
game_input = { path = "../game_input" }
game_input_model = { path = "../game_input_model" }
sequence_model = { path = "../sequence_model" }

[features]
nightly = ["amethyst/nightly"]
