[package]
name = "object_config"
version = "0.1.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", branch = "feature/634/sprite-rendering-and-animation" }
derive_more = "0.10"
derivative = "1.0"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
toml = "0.4"
