[package]
name = "stdio_input"
version = "0.9.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application_event = { path = "../application_event" }
application_input = { path = "../application_input" }
bitflags = "1.0.4"
console = "0.7.5"
derivative = "1.0.2"
derive-new = "0.5.6"
itertools = "0.8.0"
log = "0.4.6"
shell-words = "0.1.0"
state_registry = { path = "../state_registry" }
stdio_command_model = { path = "../stdio_command_model" }
stdio_spi = { path = "../stdio_spi" }
structopt = "0.2.15"
strum = "0.14.0"
typename = "0.1.0"
typename_derive = "0.1.1"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
application_robot = { path = "../application_robot" }
assert_cmd = "0.11.0"
escargot = "0.4.0"
structopt-derive = "0.2.15"

[features]
nightly = ["amethyst/nightly"]
