[package]
name = "object_loading"
version = "0.8.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application = { path = "../application" }
character_model = { path = "../character_model" }
collision_loading = { path = "../collision_loading" }
collision_model = { path = "../collision_model" }
derivative = "1.0.2"
derive-new = "0.5.6"
fnv = "1.0.6"
game_model = { path = "../game_model" }
log = "0.4.6"
object_model = { path = "../object_model" }
rayon = "1.0.3"
serde = "1.0.85"
shred = "0.7.1"
shred-derive = "0.5.1"
sprite_model = { path = "../sprite_model" }
sprite_loading = { path = "../sprite_loading" }
typename = "0.1.0"
typename_derive = "0.1.1"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
assets_test = { path = "../assets_test" }
pretty_assertions = "0.5.1"
serde = "1.0.85"
strum = "0.13.0"
tempfile = "3.0.5"

[features]
nightly = ["amethyst/nightly", "amethyst_test/nightly"]

[build-dependencies]
rustc_version = "0.2.3"

