[package]
name = "object_loading"
version = "0.8.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application = { path = "../application" }
character_model = { path = "../character_model" }
collision_loading = { path = "../collision_loading" }
collision_model = { path = "../collision_model" }
derive-new = "0.5"
fnv = "1.0"
game_model = { path = "../game_model" }
log = "0.4"
object_model = { path = "../object_model" }
sprite_loading = { path = "../sprite_loading" }

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
assets_test = { path = "../assets_test" }
pretty_assertions = "0.5"
serde = "1.0"
strum = "0.11"
tempfile = "3.0"

[features]
nightly = ["amethyst/nightly", "amethyst_test/nightly"]
