[package]
name = "object_loading"
version = "0.4.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
application = { path = "../application" }
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
derive-new = "0.5"
game_model = { path = "../game_model" }
log = "0.4"
object_model = { path = "../object_model" }

[dev-dependencies]
amethyst_test_support = { path = "../amethyst_test_support" }
pretty_assertions = "0.5"
serde = "1.0"
serde_derive = "1.0"
tempfile = "3.0"

[features]
nightly = ["amethyst/nightly", "amethyst_test_support/nightly"]
