[package]
name = "object_loading"
version = "0.9.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
animation_support = { path = "../animation_support" }
application = { path = "../application" }
asset_model = { path = "../asset_model" }
character_model = { path = "../character_model" }
collision_loading = { path = "../collision_loading" }
collision_model = { path = "../collision_model" }
derivative = "1.0.2"
derive-new = "0.5.6"
fnv = "1.0.6"
log = "0.4.6"
logic_clock = { path = "../logic_clock" }
object_model = { path = "../object_model" }
rayon = "1.0.3"
sequence_model = { path = "../sequence_model" }
serde = "1.0.89"
shred = "0.7.1"
shred-derive = "0.5.1"
sprite_loading = { path = "../sprite_loading" }
sprite_model = { path = "../sprite_model" }
typename = "0.1.0"
typename_derive = "0.1.1"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
application_event = { path = "../application_event" }
assets_test = { path = "../assets_test" }
character_loading = { path = "../character_loading" }
loading = { path = "../loading" }
map_loading = { path = "../map_loading" }
map_model = { path = "../map_model" }
pretty_assertions = "0.6.1"
sequence_loading = { path = "../sequence_loading" }
serde = "1.0.89"
strum = "0.14.0"
tempfile = "3.0.7"

[features]
nightly = ["amethyst/nightly"]
