[package]
name = "object_loading"
version = "0.2.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
amethyst_animation = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
derive-error-chain = "0.11"
derive-new = "0.5"
error-chain = "0.11"
game_model = { path = "../game_model" }
log = "0.4"
object_model = { path = "../object_model" }
toml = "0.4"

[dev-dependencies]
application = { path = "../application" }
serde = "1.0"
serde_derive = "1.0"
tempfile = "3.0"
