[package]
name = "object_loading"
version = "0.5.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application = { path = "../application" }
derive-new = "0.5"
game_model = { path = "../game_model" }
log = "0.4"
object_model = { path = "../object_model" }
sprite_loading = { path = "../sprite_loading" }

[dev-dependencies]
amethyst_test_support = { path = "../amethyst_test_support" }
assets_test = { path = "../assets_test" }
pretty_assertions = "0.5"
serde = "1.0"
serde_derive = "1.0"
strum = "0.11"
tempfile = "3.0"

[features]
nightly = ["amethyst/nightly", "amethyst_test_support/nightly"]
