[package]
name = "stdio_command_stdio"
version = "0.10.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application_event = { path = "../application_event" }
derive-new = "0.5.6"
stdio_command_model = { path = "../stdio_command_model" }
stdio_spi = { path = "../stdio_spi" }
structopt = "0.2.15"
typename = "0.1.0"
typename_derive = "0.1.1"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
state_registry = { path = "../state_registry" }

[features]
nightly = ["amethyst/nightly"]
