[package]
name = "sprite_loading"
version = "0.7.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application = { path = "../application" }
log = "0.4"
sprite_model = { path = "../sprite_model" }

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
assets_test = { path = "../assets_test" }
derive-new = "0.5"
pretty_assertions = "0.5"
