[package]
name = "sprite_loading"
version = "0.5.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
application = { path = "../application" }
game_model = { path = "../game_model" }
log = "0.4"
sprite_model = { path = "../sprite_model" }

[dev-dependencies]
amethyst_test_support = { path = "../amethyst_test_support" }
