[package]
name = "asset_derive"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.30"
proc_macro_roids = "0.2.1"
quote = "0.6.12"
syn = { version = "0.15.39", features = ["extra-traits", "visit"] }

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["test-support", "vulkan"]}

[features]
nightly = ["amethyst/nightly"]
