[package]
name = "sequence_model_derive"
version = "0.11.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.30"
proc_macro_roids = "0.2.1"
quote = "0.6.12"
syn = { version = "0.15.34", features = ["extra-traits", "visit"] }

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["test-support", "vulkan"]}
asset_derive = { path = "../asset_derive" }
derive_deref = "1.1.0"
sequence_model_spi = { path = "../sequence_model_spi" }
typename = "0.1.1"
typename_derive = "0.1.3"
