[package]
name = "sequence_model_derive"
version = "0.14.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.1"
proc_macro_roids = "0.6.0"
quote = "1.0.2"
syn = { version = "1.0.3", features = ["extra-traits", "visit"] }

[dev-dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"], branch = "maintenance/update-dependencies" }
asset_derive = { path = "../asset_derive" }
derivative = "1.0.2"
derive_deref = "1.1.0"
sequence_model_core = { path = "../sequence_model_core" }
sequence_model_spi = { path = "../sequence_model_spi" }
serde = "1.0.99"
strum = "0.15.0"
strum_macros = "0.15.0"
typename = "0.1.1"
typename_derive = "0.1.3"
