[package]
name = "collision_loading"
version = "0.7.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
animation_support = { path = "../animation_support" }
application = { path = "../application" }
collision_model = { path = "../collision_model" }
derive-new = "0.5"
shape_model = { path = "../shape_model" }
typename = "0.1"
typename_derive = "0.1"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
pretty_assertions = "0.5"
