[package]
name = "collision_loading"
version = "0.9.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
animation_support = { path = "../animation_support" }
application = { path = "../application" }
collision_model = { path = "../collision_model" }
derive-new = "0.5.6"
serde = "1.0.87"
shape_model = { path = "../shape_model" }
typename = "0.1.0"
typename_derive = "0.1.1"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
pretty_assertions = "0.5.1"

[features]
nightly = ["amethyst/nightly"]
