[package]
name = "game_mode_selection_model"
version = "0.9.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application_menu = { path = "../application_menu" }
strum = "0.14.0"
strum_macros = "0.14.0"

[features]
nightly = ["amethyst/nightly"]
