[package]
name = "asset_model"
version = "0.11.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["vulkan"] }
character_model = { path = "../character_model" }
derivative = "1.0.2"
derive-new = "0.5.6"
derive_builder = "0.7.1"
map_model = { path = "../map_model" }
object_model = { path = "../object_model" }
serde = "1.0.92"
strum = "0.15.0"
strum_macros = "0.15.0"

[dev-dependencies]
tempfile = "3.0.8"

[features]
nightly = ["amethyst/nightly"]
