[package]
name = "character_selection_ui"
version = "0.6.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application_ui = { path = "../application_ui" }
character_selection_model = { path = "../character_selection_model" }
derivative = "1.0"
derive-new = "0.5"
game_input = { path = "../game_input" }
game_model = { path = "../game_model" }
log = "0.4"
object_model = { path = "../object_model" }
strum = "0.11"
strum_macros = "0.11"
tracker = { path = "../tracker" }
typename = "0.1"
typename_derive = "0.1"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
application_test_support = { path = "../application_test_support" }
assets_test = { path = "../assets_test" }

[features]
nightly = ["amethyst/nightly", "amethyst_test/nightly"]
