[package]
name = "sequence_play"
version = "0.12.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["vulkan"] }
derivative = "1.0.2"
derive-new = "0.5.6"
log = "0.4.6"
sequence_model = { path = "../sequence_model" }
sequence_model_spi = { path = "../sequence_model_spi" }
shred = "0.7.0"
shred-derive = "0.5.1"
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["test-support", "vulkan"] }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
application_test_support = { path = "../application_test_support" }
assets_test = { path = "../assets_test" }
character_model = { path = "../character_model" }
collision_model = { path = "../collision_model" }
logic_clock = { path = "../logic_clock" }
pretty_assertions = "0.6.1"
shape_model = { path = "../shape_model" }

[features]
nightly = ["amethyst/nightly"]
