[package]
name = "object_model"
version = "0.1.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
amethyst_animation = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
derivative = "1.0"
derive_more = "0.10"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
toml = "0.4"
