[package]
name = "object_model"
version = "0.4.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", branch = "feature/829/sprite-render-pass" }
derivative = "1.0"
derive-new = "0.5"
serde = "1.0"
serde_derive = "1.0"
sprite_model = { path = "../sprite_model" }
sprite_loading = { path = "../sprite_loading" }
strum = "0.10"
strum_macros = "0.10"

[dev-dependencies]
toml = "0.4"
