[package]
name = "object_model"
version = "0.9.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
collision_loading = { path = "../collision_loading" }
collision_model = { path = "../collision_model" }
derivative = "1.0.2"
derive_deref = "1.0.2"
derive_more = "0.14.0"
derive-new = "0.5.6"
fnv = "1.0.6"
object_model_derive = { path = "../object_model_derive" }
object_model_spi = { path = "../object_model_spi" }
serde = "1.0.87"
shape_model = { path = "../shape_model" }
specs-derive = "0.4.0"
sprite_model = { path = "../sprite_model" }
sprite_loading = { path = "../sprite_loading" }
strum = "0.13.0"
strum_macros = "0.13.0"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
application = { path = "../application" }
assets_test = { path = "../assets_test" }
pretty_assertions = "0.5.1"
toml = "0.4.10"

[features]
nightly = ["amethyst/nightly"]
