[package]
name = "object_model"
version = "0.7.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
collision_loading = { path = "../collision_loading" }
collision_model = { path = "../collision_model" }
derivative = "1.0"
derive_deref = "1.0"
derive_more = "0.13"
derive-new = "0.5"
fnv = "1.0"
object_model_derive = { path = "../object_model_derive" }
serde = "1.0"
shape_model = { path = "../shape_model" }
specs-derive = "0.3"
sprite_model = { path = "../sprite_model" }
sprite_loading = { path = "../sprite_loading" }
strum = "0.11"
strum_macros = "0.11"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
pretty_assertions = "0.5"
toml = "0.4"