[package]
name = "game_mode_selection"
version = "0.6.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application_event = { path = "../application_event" }
application_menu = { path = "../application_menu" }
application_state = { path = "../application_state" }
character_selection = { path = "../character_selection" }
character_selection_ui = { path = "../character_selection_ui" }
derivative = "1.0"
derive-new = "0.5"
game_loading = { path = "../game_loading" }
game_mode_selection_model = { path = "../game_mode_selection_model" }
game_play = { path = "../game_play" }
log = "0.4"
map_selection = { path = "../map_selection" }
map_selection_ui = { path = "../map_selection_ui" }

[features]
nightly = ["amethyst/nightly"]
