[package]
name = "character_model"
version = "0.9.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
derive-new = "0.5.6"
derive_deref = "1.0.2"
derivative = "1.0.2"
object_model = { path = "../object_model" }
serde = "1.0.89"
typename = "0.1.0"
typename_derive = "0.1.1"

[dev-dependencies]
collision_model = { path = "../collision_model"}
pretty_assertions = "0.6.1"
sprite_model = { path = "../sprite_model" }
sequence_model = { path = "../sequence_model" }
toml = "0.5.0"

[features]
nightly = ["amethyst/nightly"]
