[package]
name = "character_model"
version = "0.11.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["vulkan"] }
derive-new = "0.5.6"
derive_deref = "1.0.2"
derive_more = "0.14.0"
derivative = "1.0.2"
object_model = { path = "../object_model" }
sequence_model = { path = "../sequence_model" }
serde = "1.0.91"
specs-derive = "0.4.0"
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
collision_model = { path = "../collision_model"}
pretty_assertions = "0.6.1"
shape_model = { path = "../shape_model" }
sprite_model = { path = "../sprite_model" }
toml = "0.5.0"

[features]
nightly = ["amethyst/nightly"]
