[package]
name = "character_model"
version = "0.8.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
derive-new = "0.5"
derive_deref = "1.0"
derivative = "1.0"
object_model = { path = "../object_model" }
serde = "1.0"

[dev-dependencies]
collision_model = { path = "../collision_model"}
pretty_assertions = "0.5"
sprite_model = { path = "../sprite_model" }
toml = "0.4"
