[package]
name = "workspace_tests"
version = "0.15.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dev-dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"], branch = "maintenance/update-dependencies" }
application = { path = "../application" }
lazy_static = "1.4.0"
ron = "0.5.1"
serde = "1.0.101"
serde_yaml = "0.8.9"
tempfile = "3.1.0"
