[package]
name = "workspace_tests"
version = "0.15.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dev-dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"], branch = "maintenance/update-dependencies" }
amethyst_test = { git = "https://github.com/azriel91/amethyst.git", branch = "maintenance/update-dependencies" }
application = { path = "../application" }
application_event = { path = "../application_event" }
application_input = { path = "../application_input" }
application_menu = { path = "../application_menu" }
application_robot = { path = "../application_robot" }
application_state = { path = "../application_state" }
application_test_support = { path = "../application_test_support" }
application_ui = { path = "../application_ui" }
assert_cmd = "0.11.1"
asset_model = { path = "../asset_model" }
character_selection_model = { path = "../character_selection_model" }
debug_util_amethyst = { path = "../debug_util_amethyst" }
game_input_model = { path = "../game_input_model" }
game_model = { path = "../game_model" }
lazy_static = "1.4.0"
object_type = { path = "../object_type" }
rayon = "1.2.0"
ron = "0.5.1"
serde = "1.0.101"
serde_yaml = "0.8.9"
structopt = "0.3.2"
structopt-derive = "0.3.2"
strum = "0.16.0"
strum_macros = "0.16.0"
tempfile = "3.1.0"
typename = "0.1.1"
typename_derive = "0.1.3"
winit = "0.19.3"

[features]
nightly = ["amethyst/nightly"]
