[package]
name = "workspace_tests"
version = "0.15.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dev-dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"], branch = "maintenance/update-dependencies" }
amethyst_test = { git = "https://github.com/azriel91/amethyst.git", branch = "maintenance/update-dependencies" }
application = { path = "../application" }
application_event = { path = "../application_event" }
application_input = { path = "../application_input" }
application_menu = { path = "../application_menu" }
application_robot = { path = "../application_robot" }
application_state = { path = "../application_state" }
application_test_support = { path = "../application_test_support" }
application_ui = { path = "../application_ui" }
approx = "0.3.2"
assert_cmd = "0.11.1"
asset_derive = { path = "../asset_derive" }
asset_gfx_gen = { path = "../asset_gfx_gen" }
asset_loading = { path = "../asset_loading" }
asset_model = { path = "../asset_model" }
assets_test = { path = "../assets_test" }
audio_loading = { path = "../audio_loading" }
audio_model = { path = "../audio_model" }
audio_play = { path = "../audio_play" }
camera_model = { path = "../camera_model" }
camera_play = { path = "../camera_play" }
character_loading = { path = "../character_loading" }
character_model = { path = "../character_model" }
character_play = { path = "../character_play" }
character_prefab = { path = "../character_prefab" }
character_selection = { path = "../character_selection" }
character_selection_model = { path = "../character_selection_model" }
character_selection_stdio = { path = "../character_selection_stdio" }
charge_model = { path = "../charge_model" }
collision_audio_loading = { path = "../collision_audio_loading" }
collision_loading = { path = "../collision_loading" }
collision_model = { path = "../collision_model" }
debug_util_amethyst = { path = "../debug_util_amethyst" }
derivative = "1.0.3"
derive-new = "0.5.8"
derive_deref = "1.1.0"
energy_loading = { path = "../energy_loading" }
game_input = { path = "../game_input" }
game_input_model = { path = "../game_input_model" }
game_model = { path = "../game_model" }
hamcrest = "0.1.5"
indexmap = { version = "1.2.0", features = ["serde-1"] }
kinematic_loading = { path = "../kinematic_loading" }
kinematic_model = { path = "../kinematic_model" }
lazy_static = "1.4.0"
loading = { path = "../loading" }
map_loading = { path = "../map_loading" }
map_model = { path = "../map_model" }
map_selection_model = { path = "../map_selection_model" }
object_model = { path = "../object_model" }
object_status_model = { path = "../object_status_model" }
object_type = { path = "../object_type" }
pretty_assertions = "0.6.1"
rayon = "1.2.0"
ron = "0.5.1"
sequence_loading = { path = "../sequence_loading" }
sequence_model = { path = "../sequence_model" }
serde = "1.0.101"
serde_yaml = "0.8.9"
shape_model = { path = "../shape_model" }
spawn_loading = { path = "../spawn_loading" }
sprite_loading = { path = "../sprite_loading" }
sprite_model = { path = "../sprite_model" }
stdio_spi = { path = "../stdio_spi" }
structopt = "0.3.2"
structopt-derive = "0.3.2"
strum = "0.16.0"
strum_macros = "0.16.0"
tempfile = "3.1.0"
typename = "0.1.1"
typename_derive = "0.1.3"
ui_audio_loading = { path = "../ui_audio_loading" }
winit = "0.19.3"

[features]
nightly = ["amethyst/nightly"]
