[package]
name = "game_play_state"
version = "0.4.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
character_selection = { path = "../character_selection" }
log = "0.4"
object_model = { path = "../object_model" }

[dev-dependencies]
amethyst_test_support = { path = "../amethyst_test_support" }
loading = { path = "../loading" }
object_loading = { path = "../object_loading" }

[features]
nightly = ["amethyst/nightly", "amethyst_test_support/nightly"]
