[package]
name = "object_model_derive"
version = "0.9.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.29", features = ["extra-traits", "visit"] }
quote = "0.6.11"
proc-macro2 = "0.4.27"
