[package]
name = "input_reaction_model"
version = "0.16.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
derivative = "1.0.3"
derive-new = "0.5.8"
derive_deref = "1.1.0"
game_input_model = { path = "../game_input_model" }
sequence_model = { path = "../sequence_model" }
serde = { version = "1.0.102", features = ["derive"] }

[features]
nightly = ["amethyst/nightly"]
