[package]
name = "application_state"
version = "0.6.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
amethyst_utils = { git = "https://github.com/amethyst/amethyst.git" }
application_event = { path = "../application_event" }
derivative = "1.0"
derive_deref = "1.0"
derive-new = "0.5"

[dev-dependencies]
character_selection_model = { path = "../character_selection_model" }
rayon = "1.0"

[features]
nightly = ["amethyst/nightly"]
