[package]
name = "application_state"
version = "0.6.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
application_event = { path = "../application_event" }
derivative = "1.0"
derive-new = "0.5"

[dev-dependencies]
character_selection = { path = "../character_selection" }
