[package]
name = "application_ui"
version = "0.6.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application = { path = "../application" }
application_robot = { path = "../application_robot" }
derive_more = "0.13"
serde = "1.0"
strum = "0.11"
strum_macros = "0.11"

[dev-dependencies]
amethyst_test_support = { path = "../amethyst_test_support" }
assert_cmd = "0.9"
log = "0.4"
structopt = "0.2"
structopt-derive = "0.2"

[features]
nightly = ["amethyst/nightly", "amethyst_test_support/nightly"]

[[example]]
name = "01_draw_text"
path = "examples/01_draw_text/main.rs"
