[package]
name = "application_ui"
version = "0.2.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
application = { path = "../application" }
application_robot = { path = "../application_robot" }
derive_more = "0.10"
serde = "1.0"
strum = "0.9.0"
strum_macros = "0.9.0"

[dev-dependencies]
assert_cli = "0.5"
log = "0.4"
structopt = "0.1.6"
structopt-derive = "0.1.6"

[[example]]
name = "01_draw_text"
path = "examples/01_draw_text/main.rs"
