[package]
name = "application_ui"
version = "0.1.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
application = { path = "../application" }
ron = "0.1"
serde = "1.0"
