[package]
name = "application_ui"
version = "0.5.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", branch = "bugfix/929/fix-sprite-position" }
application = { path = "../application" }
application_robot = { path = "../application_robot" }
derive_more = "0.11"
serde = "1.0"
strum = "0.10"
strum_macros = "0.10"

[dev-dependencies]
amethyst_test_support = { path = "../amethyst_test_support" }
assert_cli = "0.6"
log = "0.4"
structopt = "0.2"
structopt-derive = "0.2"

[features]
nightly = ["amethyst/nightly", "amethyst_test_support/nightly"]

[[example]]
name = "01_draw_text"
path = "examples/01_draw_text/main.rs"
