[package]
name = "application"
version = "0.11.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["vulkan"] }
derivative = "1.0.2"
derive-new = "0.5.6"
log = "0.4.6"
ron = "0.5.1"
serde = "1.0.94"
toml = "0.5.1"

[dev-dependencies]
pretty_assertions = "0.6.1"
lazy_static = "1.3.0"
tempfile = "3.0.8"

[features]
nightly = ["amethyst/nightly"]
