[package]
name = "application"
version = "0.1.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
derive-error-chain = "0.11"
error-chain = "0.11"

[dev-dependencies]
pretty_assertions = "0.4"
lazy_static = "1.0"
tempdir = "0.3"
tempfile = "2.2"
