[package]
name = "application"
version = "0.5.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", branch = "bugfix/929/fix-sprite-position" }
derivative = "1.0"
derive-error-chain = "0.11"
derive_more = "0.11"
error-chain = "0.11"
log = "0.4"
ron = "0.2"
serde = "1.0"
toml = "0.4"

[dev-dependencies]
pretty_assertions = "0.5"
lazy_static = "1.1"
tempfile = "3.0"
