[package]
name = "application"
version = "0.3.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
derivative = "1.0"
derive-error-chain = "0.11"
derive_more = "0.10"
error-chain = "0.11"
ron = "0.2"
serde = "1.0"

[dev-dependencies]
pretty_assertions = "0.4"
lazy_static = "1.0"
tempfile = "3.0"
