[package]
name = "loading"
version = "0.5.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", branch = "bugfix/929/fix-sprite-position" }
application_ui = { path = "../application_ui" }
asset_loading = { path = "../asset_loading" }
derivative = "1.0"
game_model = { path = "../game_model" }
log = "0.4"
map_loading = { path = "../map_loading" }
map_model = { path = "../map_model" }
object_loading = { path = "../object_loading" }
object_model = { path = "../object_model" }
strum = "0.10"
toml = "0.4"
