[package]
name = "loading"
version = "0.8.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application = { path = "../application" }
application_event = { path = "../application_event" }
application_state = { path = "../application_state" }
application_ui = { path = "../application_ui" }
asset_loading = { path = "../asset_loading" }
assets_built_in = { path = "../assets_built_in" }
derivative = "1.0.2"
asset_model = { path = "../asset_model" }
log = "0.4.6"
map_loading = { path = "../map_loading" }
map_model = { path = "../map_model" }
object_loading = { path = "../object_loading" }
object_model = { path = "../object_model" }
sprite_model = { path = "../sprite_model" }
sprite_loading = { path = "../sprite_loading" }
strum = "0.13.0"
toml = "0.4.10"

[build-dependencies]
rustc_version = "0.2.3"

