[package]
name = "loading"
version = "0.5.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
application_event = { path = "../application_event" }
application_state = { path = "../application_state" }
application_ui = { path = "../application_ui" }
asset_loading = { path = "../asset_loading" }
assets_built_in = { path = "../assets_built_in" }
derivative = "1.0"
game_model = { path = "../game_model" }
log = "0.4"
map_loading = { path = "../map_loading" }
map_model = { path = "../map_model" }
object_loading = { path = "../object_loading" }
object_model = { path = "../object_model" }
strum = "0.11"
toml = "0.4"
