[package]
name = "application_menu"
version = "0.8.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }

[dev-dependencies]
application = { path = "../application" }
application_robot = { path = "../application_robot" }
application_ui = { path = "../application_ui" }
assert_cmd = "0.10.2"
derivative = "1.0.2"
log = "0.4.6"
rayon = "1.0.3"
structopt = "0.2.14"
structopt-derive = "0.2.14"

[[example]]
name = "01_menu"
path = "examples/01_menu/main.rs"

[build-dependencies]
rustc_version = "0.2.3"

