[package]
name = "application_menu"
version = "0.1.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }

[dev-dependencies]
application = { path = "../application" }
application_robot = { path = "../application_robot" }
application_ui = { path = "../application_ui" }
assert_cli = "0.5"
derivative = "1.0"
log = "0.4"
rayon = "0.8"
structopt = "0.1.6"
structopt-derive = "0.1.6"

[[example]]
name = "01_menu"
path = "examples/01_menu/main.rs"
