[package]
name = "will"
description = "In this game, you make your choices; then your choices make you."
version = "0.2.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
application = { path = "../../crate/application" }
application_input = { path = "../../crate/application_input" }
application_robot = { path = "../../crate/application_robot" }
application_ui = { path = "../../crate/application_ui" }
character_selection = { path = "../../crate/character_selection" }
game_input = { path = "../../crate/game_input" }
game_mode_menu = { path = "../../crate/game_mode_menu" }
game_play = { path = "../../crate/game_play" }
loading = { path = "../../crate/loading" }
log = "0.4"
object_loading = { path = "../../crate/object_loading" }
stdio_view = { path = "../../crate/stdio_view" }
structopt = "0.1.6"
structopt-derive = "0.1.6"

[dev-dependencies]
assert_cli = "0.5"

[build-dependencies]
application = { path = "../../crate/application" }
