[package]
name = "will"
description = "In this game, you make your choices; then your choices make you."
version = "0.6.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application = { path = "../../crate/application" }
application_event = { path = "../../crate/application_event" }
application_input = { path = "../../crate/application_input" }
application_robot = { path = "../../crate/application_robot" }
application_state = { path = "../../crate/application_state" }
application_ui = { path = "../../crate/application_ui" }
character_selection_stdio = { path = "../../crate/character_selection_stdio" }
collision_loading = { path = "../../crate/collision_loading" }
collision_model = { path = "../../crate/collision_model" }
game_input = { path = "../../crate/game_input" }
game_mode_selection = { path = "../../crate/game_mode_selection" }
game_mode_selection_ui = { path = "../../crate/game_mode_selection_ui" }
game_mode_selection_stdio = { path = "../../crate/game_mode_selection_stdio" }
loading = { path = "../../crate/loading" }
map_loading = { path = "../../crate/map_loading" }
map_selection_stdio = { path = "../../crate/map_selection_stdio" }
log = "0.4"
object_loading = { path = "../../crate/object_loading" }
object_model = { path = "../../crate/object_model" }
stdio_view = { path = "../../crate/stdio_view" }
structopt = "0.2"
structopt-derive = "0.2"

[dev-dependencies]
assert_cmd = "0.9"

[build-dependencies]
application = { path = "../../crate/application" }

[features]
nightly = ["amethyst/nightly",]
