[package]
name = "will"
description = "In this game, you make your choices; then your choices make you."
version = "0.5.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", branch = "bugfix/929/fix-sprite-position" }
application = { path = "../../crate/application" }
application_input = { path = "../../crate/application_input" }
application_robot = { path = "../../crate/application_robot" }
application_ui = { path = "../../crate/application_ui" }
game_input = { path = "../../crate/game_input" }
game_mode_menu = { path = "../../crate/game_mode_menu" }
loading = { path = "../../crate/loading" }
map_loading = { path = "../../crate/map_loading" }
log = "0.4"
object_loading = { path = "../../crate/object_loading" }
object_model = { path = "../../crate/object_model" }
stdio_view = { path = "../../crate/stdio_view" }
structopt = "0.2"
structopt-derive = "0.2"

[dev-dependencies]
assert_cli = "0.6"

[build-dependencies]
application = { path = "../../crate/application" }

[features]
nightly = ["amethyst/nightly",]
