[package]
name = "application_robot"
version = "0.8.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application_input = { path = "../application_input" }
derivative = "1.0.2"

[dev-dependencies]
debug_util_amethyst = { path = "../debug_util_amethyst" }
winit = "0.18.1"

[build-dependencies]
rustc_version = "0.2.3"

