[package]
name = "application_robot"
version = "0.1.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", branch = "feature/634/sprite-rendering-and-animation" }
application_input = { path = "../application_input" }
derive_builder = "0.5"
itertools = "0.7"

[dev-dependencies]
debug_util_amethyst = { path = "../debug_util_amethyst" }
enigo = "0.0.11"
winit = "0.12"

[features]
default = []
# Used to control compilation on CI
test_ui = []
