[package]
name = "application_robot"
version = "0.5.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
application_input = { path = "../application_input" }
derivative = "1.0"
itertools = "0.7"

[dev-dependencies]
debug_util_amethyst = { path = "../debug_util_amethyst" }
enigo = "0.0.12"
winit = "0.15"

[features]
default = []
# Used to control compilation on CI
test_ui = []
