[package]
name = "application_robot"
version = "0.12.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["vulkan"] }
application_input = { path = "../application_input" }
derivative = "1.0.2"

[dev-dependencies]
debug_util_amethyst = { path = "../debug_util_amethyst" }
winit = "0.19.1"

[features]
nightly = ["amethyst/nightly"]
