[package]
name = "application_test_support"
version = "0.4.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", branch = "feature/829/sprite-render-pass" }
amethyst_test_support = { path = "../amethyst_test_support" }
character_selection = { path = "../character_selection" }
game_input = { path = "../game_input" }
object_loading = { path = "../object_loading" }
object_model = { path = "../object_model" }

[features]
nightly = ["amethyst/nightly"]
