[package]
name = "application_test_support"
version = "0.5.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", branch = "bugfix/929/fix-sprite-position" }
amethyst_test_support = { path = "../amethyst_test_support" }
application = { path = "../application" }
asset_loading = { path = "../asset_loading" }
character_selection = { path = "../character_selection" }
game_input = { path = "../game_input" }
game_loading = { path = "../game_loading" }
game_model = { path = "../game_model" }
lazy_static = "1.1"
loading = { path = "../loading" }
map_loading = { path = "../map_loading" }
map_model = { path = "../map_model" }
map_selection = { path = "../map_selection" }
object_loading = { path = "../object_loading" }
object_model = { path = "../object_model" }

[dev-dependencies]
strum = "0.10"

[features]
nightly = ["amethyst/nightly"]
