[package]
name = "character_selection_model"
version = "0.11.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["vulkan"] }
asset_model = { path = "../asset_model" }
character_loading = { path = "../character_loading" }
character_model = { path = "../character_model" }
derivative = "1.0.2"
derive-new = "0.5.6"
game_input_model = { path = "../game_input_model" }
object_model = { path = "../object_model" }
strum = "0.15.0"
strum_macros = "0.15.0"

[features]
nightly = ["amethyst/nightly"]
