[package]
name = "assets_test"
version = "0.11.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"
publish = false

[dependencies]
asset_model = { path = "../asset_model" }
heck = "0.3.1"
lazy_static = "1.3.0"
object_type = { path = "../object_type" }
strum = "0.15.0"
