[package]
name = "assets_test"
version = "0.8.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"
publish = false

[dependencies]
game_model = { path = "../game_model" }
heck = "0.3"
lazy_static = "1.1"
object_model = { path = "../object_model" }
strum = "0.11"
