[package]
name = "assets_test"
version = "0.10.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"
publish = false

[dependencies]
asset_model = { path = "../asset_model" }
heck = "0.3.1"
lazy_static = "1.3.0"
object_model = { path = "../object_model" }
strum = "0.14.0"
