[package]
name = "stdio_view"
version = "0.5.0"
authors = ["Azriel Hoh <azriel91@gmail.com>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
application_event = { path = "../application_event" }
application_input = { path = "../application_input" }
console = "0.6"
derive-new = "0.5"
fern = "0.5"
itertools = "0.7"
log = "0.4"
shell-words = "0.1"
stdio_spi = { path = "../stdio_spi" }
structopt = "0.2"
strum = "0.10"
typename = "0.1"
typename_derive = "0.1"

[dev-dependencies]
application_robot = { path = "../application_robot" }
amethyst_test_support = { path = "../amethyst_test_support" }
assert_cli = "0.6"
structopt = "0.2"
structopt-derive = "0.2"

[features]
nightly = ["amethyst/nightly", "amethyst_test_support/nightly"]
