[package]
name = "stdio_view"
version = "0.1.0"
authors = ["Azriel Hoh <azriel91@gmail.com>"]

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", branch = "feature/634/sprite-rendering-and-animation" }
application_input = { path = "../application_input" }
console = "0.6"
fern = "0.5"
log = "0.4"
