[package]
name = "game_input_model"
version = "0.10.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
derivative = "1.0.2"
derive-new = "0.5.6"
log = "0.4.6"
serde = { version = "1.0.90", features = ["derive"] }
strum = "0.15.0"
strum_macros = "0.15.0"

[dev-dependencies]
hamcrest = "0.1.5"
winit = "0.18.1"

[features]
nightly = ["amethyst/nightly"]
