[package]
name = "game_loading"
version = "0.11.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["vulkan"] }
animation_support = { path = "../animation_support" }
application_event = { path = "../application_event" }
application_state = { path = "../application_state" }
character_loading = { path = "../character_loading" }
character_model = { path = "../character_model" }
character_selection_model = { path = "../character_selection_model" }
collision_model = { path = "../collision_model" }
derivative = "1.0.2"
derive-new = "0.5.6"
game_input = { path = "../game_input" }
game_model = { path = "../game_model" }
game_play_hud = { path = "../game_play_hud" }
game_play_model = { path = "../game_play_model" }
log = "0.4.6"
logic_clock = { path = "../logic_clock" }
map_model = { path = "../map_model" }
map_selection_model = { path = "../map_selection_model" }
num-traits = "0.2.6"
object_loading = { path = "../object_loading" }
object_model = { path = "../object_model" }
sequence_model = { path = "../sequence_model" }
shred = "0.7.0"
shred-derive = "0.5.1"
state_registry = { path = "../state_registry" }
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
asset_loading = { path = "../asset_loading" }
asset_model = { path = "../asset_model" }
assets_test = { path = "../assets_test" }
collision_audio_loading = { path = "../collision_audio_loading" }
collision_loading = { path = "../collision_loading" }
loading = { path = "../loading" }
map_loading = { path = "../map_loading" }
map_selection = { path = "../map_selection" }
sequence_loading = { path = "../sequence_loading" }
sprite_loading = { path = "../sprite_loading" }
ui_audio_loading = { path = "../../crate/ui_audio_loading" }

[features]
nightly = ["amethyst/nightly"]
