[package]
name = "game_loading"
version = "0.5.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", branch = "feature/829/sprite-render-pass" }
character_selection = { path = "../character_selection" }
derivative = "1.0"
derive-new = "0.5"
game_model = { path = "../game_model" }
log = "0.4"
map_model = { path = "../map_model" }
map_selection = { path = "../map_selection" }
object_model = { path = "../object_model" }

[dev-dependencies]
amethyst_test_support = { path = "../amethyst_test_support" }
loading = { path = "../loading" }
map_loading = { path = "../map_loading" }
object_loading = { path = "../object_loading" }
typename = "0.1"
typename_derive = "0.1"

[features]
nightly = ["amethyst/nightly", "amethyst_test_support/nightly"]
