[package]
name = "map_selection_stdio"
version = "0.6.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application_event = { path = "../application_event" }
map_selection_model = { path = "../map_selection_model" }
derive-new = "0.5"
game_model = { path = "../game_model" }
stdio_spi = { path = "../stdio_spi" }
structopt = "0.2"
structopt-derive = "0.2"
typename = "0.1"
typename_derive = "0.1"

[dev-dependencies]
amethyst_test_support = { path = "../amethyst_test_support" }
application_test_support = { path = "../application_test_support" }
assets_test = { path = "../assets_test" }
