[package]
name = "character_selection"
version = "0.6.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application_event = { path = "../application_event" }
application_state = { path = "../application_state" }
character_selection_model = { path = "../character_selection_model" }
derivative = "1.0"
derive-new = "0.5"
log = "0.4"
object_model = { path = "../object_model" }
typename = "0.1"
typename_derive = "0.1"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
asset_loading = { path = "../asset_loading" }
assets_test = { path = "../assets_test" }
collision_loading = { path = "../collision_loading" }
collision_model = { path = "../collision_model" }
game_input = { path = "../game_input" }
game_model = { path = "../game_model" }
loading = { path = "../loading" }
map_loading = { path = "../map_loading" }
object_loading = { path = "../object_loading" }

[features]
nightly = ["amethyst/nightly", "amethyst_test/nightly"]
