[package]
name = "character_selection"
version = "0.3.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
derivative = "1.0"
derive-new = "0.5"
game_input = { path = "../game_input" }
game_model = { path = "../game_model" }
log = "0.4"
object_model = { path = "../object_model" }
