[package]
name = "application_input"
version = "0.1.0"
authors = ["Azriel Hoh <azriel91@gmail.com>"]

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", branch = "feature/634/sprite-rendering-and-animation" }
