[package]
name = "application_input"
version = "0.5.0"
authors = ["Azriel Hoh <azriel91@gmail.com>"]

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", branch = "bugfix/929/fix-sprite-position" }
