[package]
name = "tracker"
version = "0.8.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
derive-new = "0.5.6"
named_type = "0.1.6"
named_type_derive = "0.1.6"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }

[build-dependencies]
rustc_version = "0.2.3"

