[package]
name = "shape_model"
version = "0.9.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
serde = "1.0.85"
strum = "0.13.0"
strum_macros = "0.13.0"

[build-dependencies]
rustc_version = "0.2.3"

