[package]
name = "game_input_stdio"
version = "0.9.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application_event = { path = "../application_event" }
derive-new = "0.5.6"
game_input = { path = "../game_input" }
game_input_model = { path = "../game_input_model" }
stdio_spi = { path = "../stdio_spi" }
structopt = "0.2.14"
structopt-derive = "0.2.14"
strum = "0.13.0"
strum_macros = "0.13.0"
typename = "0.1.0"
typename_derive = "0.1.1"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
application_test_support = { path = "../application_test_support" }

[build-dependencies]
rustc_version = "0.2.3"

