[package]
name = "map_loading"
version = "0.5.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application = { path = "../application" }
derive-new = "0.5"
log = "0.4"
map_model = { path = "../map_model" }
sprite_loading = { path = "../sprite_loading" }

[dev-dependencies]
amethyst_test_support = { path = "../amethyst_test_support" }
assets_test = { path = "../assets_test" }
