[package]
name = "map_loading"
version = "0.7.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application = { path = "../application" }
derive-new = "0.5"
log = "0.4"
map_model = { path = "../map_model" }
sprite_loading = { path = "../sprite_loading" }

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
assets_test = { path = "../assets_test" }
