[package]
name = "chase_model"
version = "0.11.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["vulkan"] }
derive-new = "0.5.6"
serde = "1.0.94"
specs-derive = "0.4.0"

[features]
nightly = ["amethyst/nightly"]
