[package]
name = "test_object_model"
version = "0.12.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["vulkan"] }
asset_derive = { path = "../asset_derive" }
derivative = "1.0.2"
derive-new = "0.5.6"
object_model = { path = "../object_model" }
object_type = { path = "../object_type", features = ["test-support"] }
sequence_model = { path = "../sequence_model" }
serde = "1.0.94"
strum = "0.15.0"
strum_macros = "0.15.0"
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["test-support", "vulkan"] }
sprite_model = { path = "../sprite_model" }
toml = "0.5.1"

[features]
nightly = ["amethyst/nightly"]
