[package]
name = "game_play"
version = "0.3.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
character_selection = { path = "../character_selection" }
derive-new = "0.5"
game_input = { path = "../game_input" }
game_model = { path = "../game_model" }
log = "0.4"
object_model = { path = "../object_model" }
object_play = { path = "../object_play" }

[dev-dependencies]
application = { path = "../application" }
loading = { path = "../loading" }
object_loading = { path = "../object_loading" }
