[package]
name = "game_play"
version = "0.7.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application_event = { path = "../application_event" }
character_selection = { path = "../character_selection" }
collision_model = { path = "../collision_model" }
derivative = "1.0"
derive-new = "0.5"
game_input = { path = "../game_input" }
game_loading = { path = "../game_loading" }
game_model = { path = "../game_model" }
game_play_model = { path = "../game_play_model" }
log = "0.4"
map_model = { path = "../map_model" }
map_selection_model = { path = "../map_selection_model" }
object_model = { path = "../object_model" }
object_play = { path = "../object_play" }
shape_model = { path = "../shape_model" }
tracker = { path = "../tracker" }
typename = "0.1"
typename_derive = "0.1"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
application = { path = "../application" }
application_test_support = { path = "../application_test_support" }
loading = { path = "../loading" }
object_loading = { path = "../object_loading" }

[features]
nightly = ["amethyst/nightly", "amethyst_test/nightly"]
