[package]
name = "game_play"
version = "0.4.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
character_selection = { path = "../character_selection" }
derive-new = "0.5"
game_input = { path = "../game_input" }
game_model = { path = "../game_model" }
game_play_state = { path = "../game_play_state" }
map_model = { path = "../map_model" }
object_model = { path = "../object_model" }
object_play = { path = "../object_play" }
typename = "0.1"
typename_derive = "0.1"

[dev-dependencies]
amethyst_test_support = { path = "../amethyst_test_support" }
application_test_support = { path = "../application_test_support" }
loading = { path = "../loading" }
object_loading = { path = "../object_loading" }

[features]
nightly = ["amethyst/nightly", "amethyst_test_support/nightly"]
