[package]
name = "game_play"
version = "0.9.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
animation_support = { path = "../animation_support" }
application_event = { path = "../application_event" }
character_model = { path = "../character_model" }
character_selection = { path = "../character_selection" }
collision_model = { path = "../collision_model" }
derivative = "1.0.2"
derive-new = "0.5.6"
game_input = { path = "../game_input" }
game_model = { path = "../game_model" }
game_play_model = { path = "../game_play_model" }
log = "0.4.6"
map_model = { path = "../map_model" }
map_selection_model = { path = "../map_selection_model" }
named_type = "0.2.1"
named_type_derive = "0.2.1"
object_loading = { path = "../object_loading" }
object_model = { path = "../object_model" }
object_play = { path = "../object_play" }
shape_model = { path = "../shape_model" }
shred = "0.7.1"
shred-derive = "0.5.1"
tracker = { path = "../tracker" }
typename = "0.1.0"
typename_derive = "0.1.1"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
application = { path = "../application" }
application_test_support = { path = "../application_test_support" }
game_input_model = { path = "../game_input_model" }
loading = { path = "../loading" }

[features]
nightly = ["amethyst/nightly"]
