[package]
name = "game_play"
version = "0.2.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
application_ui = { path = "../application_ui" }
character_selection = { path = "../character_selection" }
derive-new = "0.5"
game_input = { path = "../game_input" }
game_model = { path = "../game_model" }
log = "0.4"
object_model = { path = "../object_model" }
