[package]
name = "game_play"
version = "0.11.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["vulkan"] }
animation_support = { path = "../animation_support" }
application_event = { path = "../application_event" }
character_model = { path = "../character_model" }
character_play = { path = "../character_play" }
character_selection = { path = "../character_selection" }
collision_audio_play = { path = "../collision_audio_play" }
collision_model = { path = "../collision_model" }
collision_play = { path = "../collision_play" }
derivative = "1.0.2"
derive-new = "0.5.6"
game_input = { path = "../game_input" }
game_model = { path = "../game_model" }
game_play_hud = { path = "../game_play_hud" }
game_play_model = { path = "../game_play_model" }
kinematic_model = { path = "../kinematic_model" }
log = "0.4.6"
logic_clock = { path = "../logic_clock" }
map_model = { path = "../map_model" }
map_selection_model = { path = "../map_selection_model" }
named_type = "0.2.1"
named_type_derive = "0.2.1"
object_model = { path = "../object_model" }
object_play = { path = "../object_play" }
object_prefab = { path = "../object_prefab" }
object_status_model = { path = "../object_status_model" }
object_status_play = { path = "../object_status_play" }
sequence_model = { path = "../sequence_model" }
sequence_play = { path = "../sequence_play" }
shape_model = { path = "../shape_model" }
shred = "0.7.0"
shred-derive = "0.5.1"
sprite_model = { path = "../sprite_model" }
state_registry = { path = "../state_registry" }
tracker = { path = "../tracker" }
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["test-support", "vulkan"] }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
application = { path = "../application" }
application_test_support = { path = "../application_test_support" }
assets_test = { path = "../assets_test" }
game_input_model = { path = "../game_input_model" }
loading = { path = "../loading" }

[features]
nightly = ["amethyst/nightly"]
