[package]
name = "asset_loading"
version = "0.8.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application = { path = "../application" }
derive-new = "0.5.6"
asset_model = { path = "../asset_model" }
heck = "0.3.1"
itertools = "0.8.0"
log = "0.4.6"
map_model = { path = "../map_model" }
object_model = { path = "../object_model" }
serde = "1.0.85"
strum = "0.13.0"
toml = "0.4.10"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
derive_deref = "1.0.1"
hamcrest = "0.1.5"
pretty_assertions = "0.5.1"
tempfile = "3.0.5"

[build-dependencies]
rustc_version = "0.2.3"

