[package]
name = "game_mode_menu"
version = "0.3.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
application_menu = { path = "../application_menu" }
application_ui = { path = "../application_ui" }
character_selection = { path = "../../crate/character_selection" }
derivative = "1.0"
game_play = { path = "../game_play" }
log = "0.4"
rayon = "1.0"

[dev-dependencies]
debug_util_amethyst = { path = "../debug_util_amethyst" }
