[package]
name = "game_mode_menu"
version = "0.1.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
application_input = { path = "../application_input" }

[dev-dependencies]
enigo = "0.0.11"
lazy_static = "1.0"
winit = "0.10"
