[package]
name = "game_mode_menu"
version = "0.4.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", branch = "feature/829/sprite-render-pass" }
application_menu = { path = "../application_menu" }
application_ui = { path = "../application_ui" }
character_selection = { path = "../../crate/character_selection" }
derivative = "1.0"
game_play_state = { path = "../../crate/game_play_state" }
log = "0.4"
map_selection = { path = "../../crate/map_selection" }
rayon = "1.0"

[dev-dependencies]
amethyst_test_support = { path = "../amethyst_test_support" }
debug_util_amethyst = { path = "../debug_util_amethyst" }

[features]
nightly = ["amethyst/nightly", "amethyst_test_support/nightly"]
