[package]
name = "character_loading"
version = "0.9.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
character_model = { path = "../character_model" }
derivative = "1.0"
derive-new = "0.5"
game_input = { path = "../game_input" }
object_loading = { path = "../object_loading" }
object_model = { path = "../object_model" }
serde = "1.0"
shred = "0.7.1"
shred-derive = "0.5.1"
typename = "0.1.0"
