[package]
name = "character_loading"
version = "0.9.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
application = { path = "../application" }
character_model = { path = "../character_model" }
derivative = "1.0.2"
derive-new = "0.5.6"
game_input = { path = "../game_input" }
object_loading = { path = "../object_loading" }
object_model = { path = "../object_model" }
serde = "1.0.87"
shred = "0.7.1"
shred-derive = "0.5.1"
typename = "0.1.0"
typename_derive = "0.1.1"

[dev-dependencies]
asset_model = { path = "../asset_model" }
assets_test = { path = "../assets_test" }
collision_loading = { path = "../collision_loading" }
collision_model = { path = "../collision_model" }
sprite_loading = { path = "../sprite_loading" }
sprite_model = { path = "../sprite_model" }

[features]
nightly = ["amethyst/nightly"]
