[package]
name = "map_selection_ui"
version = "0.6.0"
authors = ["Azriel Hoh <mail@azriel.im>"]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }
application_ui = { path = "../application_ui" }
derivative = "1.0"
derive-new = "0.5"
game_input = { path = "../game_input" }
game_model = { path = "../game_model" }
log = "0.4"
map_model = { path = "../map_model" }
map_selection = { path = "../map_selection" }
map_selection_model = { path = "../map_selection_model" }
strum = "0.10"
strum_macros = "0.10"
tracker = { path = "../tracker" }
typename = "0.1"
typename_derive = "0.1"

[dev-dependencies]
amethyst_test_support = { path = "../amethyst_test_support" }
application_test_support = { path = "../application_test_support" }
assets_test = { path = "../assets_test" }

[features]
nightly = ["amethyst/nightly", "amethyst_test_support/nightly"]
