[package]
name = "map_selection_ui"
version = "0.10.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
application_ui = { path = "../application_ui" }
asset_model = { path = "../asset_model" }
derivative = "1.0.2"
derive-new = "0.5.6"
game_input = { path = "../game_input" }
game_input_model = { path = "../game_input_model" }
game_model = { path = "../game_model" }
log = "0.4.6"
map_model = { path = "../map_model" }
map_selection_model = { path = "../map_selection_model" }
shred = "0.7.0"
shred-derive = "0.5.1"
strum = "0.15.0"
strum_macros = "0.15.0"
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
application_test_support = { path = "../application_test_support" }
assets_test = { path = "../assets_test" }

[features]
nightly = ["amethyst/nightly"]
