[package]
name = "ui_model"
version = "0.15.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
asset_derive = { path = "../asset_derive" }
asset_model = { path = "../asset_model" }
game_mode_selection_model = { path = "../game_mode_selection_model" }
serde = { version = "1.0.101", features = ["derive"] }
slotmap = { version = "0.4.0", features = ["serde"] }
ui_menu_item_model = { path = "../ui_menu_item_model" }

[features]
nightly = ["amethyst/nightly"]
