[package]
name = "game_play_model"
version = "0.12.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["vulkan"] }

[features]
nightly = ["amethyst/nightly"]
