[package]
name = "numeric_newtype_derive"
version = "0.10.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.27"
quote = "0.6.11"
syn = { version = "0.15.29", features = ["extra-traits", "visit"] }

[dev-dependencies]
derive_more = "0.14.0"
