[package]
name = "character_selection_ui_model"
version = "0.16.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
indexmap = { version = "1.3.0", features = ["serde-1"] }
kinematic_model = { path = "../kinematic_model" }
serde = { version = "1.0.102", features = ["derive"] }
sequence_model = { path = "../sequence_model" }
sprite_model = { path = "../sprite_model" }
ui_label_model = { path = "../ui_label_model" }
