[package]
name = "energy_loading"
version = "0.12.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["vulkan"] }
energy_model = { path = "../energy_model" }
derivative = "1.0.2"
derive-new = "0.5.6"
object_loading = { path = "../object_loading" }
typename = "0.1.1"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["test-support", "vulkan"] }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
sequence_loading = { path = "../sequence_loading" }

[features]
nightly = ["amethyst/nightly"]
