[package]
name = "game_input_ui"
version = "0.9.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
approx = { git = "https://github.com/brendanzab/approx.git" }
derive-new = "0.5.6"
game_input = { path = "../game_input"}
game_input_model = { path = "../game_input_model" }
strum = "0.14.0"
strum_macros = "0.14.0"
typename = "0.1.0"
typename_derive = "0.1.1"

[dev-dependencies]
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
hamcrest = "0.1.5"
winit = "0.18.1"